import './globals.css'
import {  Montserrat } from 'next/font/google'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'

const montserrat = Montserrat({ subsets: ['latin'], 
weight : ['300'],
style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'TK Agency',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <Navbar />
        
        {children}
<Footer />
       
        </body>
        <Navbar />
    </html>
  )
}
